# Generated by Django 4.2.8 on 2024-07-01 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import yeastregulatorydb.regulatory_data.models.mixins.GzipFileUploadWithIdMixin


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Binding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upload_date", models.DateField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.CharField(
                        default="none",
                        help_text="A batch identifier for a set of data, eg the run number in the case of calling cards",
                        max_length=20,
                    ),
                ),
                ("replicate", models.PositiveIntegerField(default=1, help_text="Replicate number")),
                (
                    "source_orig_id",
                    models.CharField(
                        default="none",
                        help_text="If the data was provided by a third party, and that data has a unique identifier, it is provided here. Otherwise, the value  is `none`",
                        max_length=20,
                    ),
                ),
                (
                    "strain",
                    models.CharField(
                        default="unknown",
                        help_text="If the strain identifier is known, it is provided. Otherwise, the value is `unknown`",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("unknown", "unknown"),
                            ("YPD", "YPD"),
                            ("SM", "SM"),
                            ("RAPA", "RAPA"),
                            ("H2O2Hi", "H2O2Hi"),
                            ("H2O2Lo", "H2O2Lo"),
                            ("Acid", "Acid"),
                            ("Alpha", "Alpha"),
                            ("BUT14", "BUT14"),
                            ("BUT90", "BUT90"),
                            ("Thi-", "Thi-"),
                            ("GAL", "GAL"),
                            ("HEAT", "HEAT"),
                            ("Pi-", "Pi-"),
                            ("RAFF", "RAFF"),
                        ],
                        default="unknown",
                        help_text="If the condition is known, it is provided. Otherwise, the value is `unknown`",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="A file which stores data on regulator/DNA interaction",
                        null=True,
                        upload_to="temp",
                    ),
                ),
                (
                    "genomic_inserts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of inserts which map to chromosomes labelled as `genomic` in the ChrMap table",
                    ),
                ),
                (
                    "mito_inserts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of inserts which map to chromosomes labelled as mitochondrial in the ChrMap table",
                    ),
                ),
                (
                    "plasmid_inserts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of inserts which map to contigs labelled as plasmid in the ChrMap table",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        default="none", help_text="free entry text field, no more than 100 char long", max_length=100
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modifier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "binding",
            },
            bases=(
                models.Model,
                yeastregulatorydb.regulatory_data.models.mixins.GzipFileUploadWithIdMixin.GzipFileUploadWithIdMixin,
            ),
        ),
        migrations.CreateModel(
            name="BindingConcatenated",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "genomic_inserts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of inserts which map to chromosomes labelled as `genomic` in the ChrMap table",
                    ),
                ),
                (
                    "mito_inserts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of inserts which map to chromosomes labelled as mitochondrial in the ChrMap table",
                    ),
                ),
                (
                    "plasmid_inserts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of inserts which map to contigs labelled as plasmid in the ChrMap table",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        default="none", help_text="Free entry text field, no more than 100 char long", max_length=100
                    ),
                ),
                ("bindings", models.ManyToManyField(to="regulatory_data.binding")),
            ],
            options={
                "db_table": "bindingconcatenated",
            },
        ),
        migrations.CreateModel(
            name="CallingCardsBackground",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upload_date", models.DateField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="The name of the background data", max_length=10, unique=True)),
                (
                    "file",
                    models.FileField(
                        help_text="A file which stores data on regulator/DNA interaction", upload_to="temp"
                    ),
                ),
                (
                    "genomic_inserts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of inserts which map to chromosomes with type `genomic` in ChrMap",
                    ),
                ),
                (
                    "mito_inserts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of inserts which map to chromosomes with type `mitochondrial` in ChrMap",
                    ),
                ),
                (
                    "plasmid_inserts",
                    models.PositiveIntegerField(
                        default=0, help_text="The number of inserts which map to contigs with type `plasmid` in ChrMap"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        default="none", help_text="free entry text field, no more than 100 char long", max_length=100
                    ),
                ),
            ],
            options={
                "db_table": "callingcardsbackground",
            },
            bases=(
                models.Model,
                yeastregulatorydb.regulatory_data.models.mixins.GzipFileUploadWithIdMixin.GzipFileUploadWithIdMixin,
            ),
        ),
        migrations.CreateModel(
            name="ChrMap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upload_date", models.DateField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("refseq", models.CharField(help_text="RefSeq chr identifiers", max_length=12, unique=True)),
                ("igenomes", models.CharField(help_text="iGenomes chr identifiers", max_length=12, unique=True)),
                ("ensembl", models.CharField(help_text="Ensembl chr identifiers", max_length=12, unique=True)),
                ("ucsc", models.CharField(help_text="UCSC chr identifiers", max_length=12, unique=True)),
                ("mitra", models.CharField(help_text="Mitra chr identifiers", max_length=15, unique=True)),
                ("numbered", models.CharField(help_text="Numbered chr identifiers", max_length=12, unique=True)),
                ("chr", models.CharField(help_text="Chromosome number or identifier", max_length=12, unique=True)),
                ("seqlength", models.PositiveIntegerField(help_text="Sequence length of a given chromosome/contig")),
                (
                    "type",
                    models.CharField(
                        choices=[("genomic", "genomic"), ("mito", "mito"), ("plasmid", "plasmid")],
                        default="genomic",
                        help_text="Chromosome type, one of genomic, mito or plasmid",
                        max_length=8,
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modifier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_uploader",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chrmap",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upload_date", models.DateField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="A unique name for the data source, eg 'chipexo_pugh_allevents",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("lab", models.CharField(help_text="The name of the lab which generated the data", max_length=20)),
                ("assay", models.CharField(help_text="name of the assay used to generate the data", max_length=20)),
                (
                    "workflow",
                    models.CharField(
                        default="undefined",
                        help_text="The workflow used to generate the data, including version",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        default="none",
                        help_text="A description of the data. include a URL to github repo with scripts describing how the data was parsed",
                        max_length=400,
                    ),
                ),
                ("citation", models.CharField(default="ask_admin", help_text="citation for the data", max_length=400)),
                (
                    "notes",
                    models.CharField(
                        default="none",
                        help_text="Any additional notes about the source of the binding data",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "db_table": "datasource",
            },
        ),
        migrations.CreateModel(
            name="Expression",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upload_date", models.DateField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.CharField(
                        db_index=True,
                        default="undefined",
                        help_text="A batch identifier for a set of data, eg the run number in the case of calling cards",
                        max_length=20,
                    ),
                ),
                (
                    "strain",
                    models.CharField(
                        default="undefined",
                        help_text="The strain used in the experiment. This will be derived from the original data source. Default value is `undefined`",
                        max_length=20,
                    ),
                ),
                ("replicate", models.PositiveIntegerField(db_index=True, default=1, help_text="Replicate number")),
                (
                    "control",
                    models.CharField(
                        choices=[("undefined", "undefined"), ("wt", "wt"), ("wt_mata", "wt_mata")],
                        db_index=True,
                        default="undefined",
                        help_text="Intended for micro-array data, this field records the control strain used to generate the relative intensity data",
                    ),
                ),
                (
                    "mechanism",
                    models.CharField(
                        choices=[("gev", "gev"), ("zev", "zev"), ("tfko", "tfko")],
                        db_index=True,
                        default="undefined",
                        help_text="The mechanism by which the regulator was perturbed",
                        max_length=10,
                    ),
                ),
                (
                    "restriction",
                    models.CharField(
                        choices=[("undefined", "undefined"), ("P", "P"), ("M", "M"), ("N", "N")],
                        db_index=True,
                        default="undefined",
                        help_text="This is a feature of the McIsaac ZEV data",
                        max_length=10,
                    ),
                ),
                (
                    "time",
                    models.FloatField(db_index=True, default=0, help_text="Timepoint of the experiment in minutes"),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="A file which stores gene expression data that results from a given regulator perturbation",
                        upload_to="temp",
                    ),
                ),
                (
                    "notes",
                    models.CharField(default="none", help_text="Free entry notes about the data", max_length=100),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modifier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "expression",
            },
            bases=(
                models.Model,
                yeastregulatorydb.regulatory_data.models.mixins.GzipFileUploadWithIdMixin.GzipFileUploadWithIdMixin,
            ),
        ),
        migrations.CreateModel(
            name="FileFormat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upload_date", models.DateField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "fileformat",
                    models.CharField(
                        db_index=True,
                        help_text="A file format name. This should be short, eg 'bed' or 'qbed' or 'tsv'",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "fields",
                    models.JSONField(
                        help_text='A JSON key:value set of columns and expected datatypes. Eg {"chr": "str","start": "int","end": "int","name": "str","score": "float","strand": ["+", "-", "*"]}'
                    ),
                ),
                (
                    "separator",
                    models.CharField(
                        choices=[("\t", "tab"), (",", "comma")],
                        default="\t",
                        help_text="The separator used in the file. Defaults to tab.",
                        max_length=2,
                    ),
                ),
                (
                    "feature_identifier_col",
                    models.CharField(
                        default="none",
                        help_text="The name of the column that should be used as the default feature identifier column. Eg 'name'. Defaults to 'none'.",
                        max_length=40,
                    ),
                ),
                (
                    "effect_col",
                    models.CharField(
                        default="none",
                        help_text="The name of the column that should be used as the default effect column. Eg 'score'. Defaults to 'none' if there is no effect column.",
                        max_length=40,
                    ),
                ),
                (
                    "default_effect_threshold",
                    models.FloatField(
                        default=0.0, help_text="The default threshold for the effect column. Defaults to 0.0."
                    ),
                ),
                (
                    "pval_col",
                    models.CharField(
                        default="none",
                        help_text="The name of the column that should be used as the default p-value column. Eg 'pvalue'. Defaults to 'none' if there is no p-value column.",
                        max_length=40,
                    ),
                ),
                (
                    "default_pvalue_threshold",
                    models.FloatField(
                        default=1.0, help_text="The default threshold for the p-value column. Defaults to 1.0."
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modifier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_uploader",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fileformat",
            },
        ),
        migrations.CreateModel(
            name="GenomicFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upload_date", models.DateField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("start", models.PositiveIntegerField(db_index=True, help_text="start position of the feature")),
                ("end", models.PositiveIntegerField(db_index=True, help_text="end position of the feature")),
                (
                    "strand",
                    models.CharField(
                        choices=[("+", "+"), ("-", "-"), ("*", "*")],
                        default="*",
                        help_text="strand of the feature, one of +, -, or *",
                        max_length=1,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        default="unknown",
                        help_text="CharField with a max length of 30, representing the type of the genomic feature, eg 'gene' or 'tRNA_gene'",
                        max_length=30,
                    ),
                ),
                (
                    "locus_tag",
                    models.CharField(
                        db_index=True,
                        default="unknown",
                        help_text="CharField with a max length of 20 and a unique constraint, representing the locus tag of the feature, eg YAL001C",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True,
                        default="unknown",
                        help_text="CharField with a max length of 20, representing the feature symbol (eg GAL4)",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="CharField with a max length of 50, representing the source of the feature information",
                        max_length=50,
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        default="unknown",
                        help_text="CharField with a max length of 150, representing the alias of the feature",
                        max_length=150,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        default="none",
                        help_text="CharField with a max length of 1000, representing any notes about the feature",
                        max_length=1000,
                    ),
                ),
                (
                    "chr",
                    models.ForeignKey(
                        help_text="foreign key to the `id` field of ChrMap",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regulatory_data.chrmap",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modifier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_uploader",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "genomicfeature",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PromoterSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upload_date", models.DateField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the promoter set, eg `orf` or `yiming`",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="A bed format file where each row describes a regulatory region of a given target feature, which is identified in the 'name' column by the GenomicFeature id",
                        upload_to="temp",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        default="none", help_text="free entry text field, no more than 100 char long", max_length=500
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modifier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_uploader",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "promoterset",
            },
            bases=(
                models.Model,
                yeastregulatorydb.regulatory_data.models.mixins.GzipFileUploadWithIdMixin.GzipFileUploadWithIdMixin,
            ),
        ),
        migrations.CreateModel(
            name="Regulator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upload_date", models.DateField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "under_development",
                    models.BooleanField(
                        default=False,
                        help_text="whether the regulator is being currently interrogated in any experiments",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        default="none", help_text="free entry text field, no more than 50 char long", max_length=50
                    ),
                ),
                (
                    "genomicfeature",
                    models.ForeignKey(
                        help_text="foreign key to the `id` field of GenomicFeature",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="regulatory_data.genomicfeature",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modifier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_uploader",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "regulator",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PromoterSetSig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upload_date", models.DateField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        help_text="A file which stores data on regulator/DNA interaction", upload_to="temp"
                    ),
                ),
                (
                    "background",
                    models.ForeignKey(
                        blank=True,
                        help_text="foreign key to the 'CallingCardsBackground' table",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regulatory_data.callingcardsbackground",
                    ),
                ),
                (
                    "composite_binding",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key to the 'BindingConcatenated' table",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promoter_set_sigs",
                        to="regulatory_data.bindingconcatenated",
                    ),
                ),
                (
                    "fileformat",
                    models.ForeignKey(
                        help_text="foreign key to the 'FileFormat' table",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regulatory_data.fileformat",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modifier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promoter",
                    models.ForeignKey(
                        blank=True,
                        help_text="foreign key to the 'promoter' table",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regulatory_data.promoterset",
                    ),
                ),
                (
                    "single_binding",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key to the 'Binding' table",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promoter_set_sigs",
                        to="regulatory_data.binding",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_uploader",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "promotersetsig",
            },
            bases=(
                models.Model,
                yeastregulatorydb.regulatory_data.models.mixins.GzipFileUploadWithIdMixin.GzipFileUploadWithIdMixin,
            ),
        ),
        migrations.CreateModel(
            name="ExpressionManualQC",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upload_date", models.DateField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "strain_verified",
                    models.CharField(
                        choices=[("yes", "yes"), ("no", "no"), ("unverified", "unverified")],
                        default="unverified",
                        help_text="whether the strain is verified",
                        max_length=10,
                    ),
                ),
                (
                    "expression",
                    models.OneToOneField(
                        help_text="foreign key to the expression table",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regulatory_data.expression",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modifier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_uploader",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "expressionmanualqc",
            },
        ),
        migrations.AddField(
            model_name="expression",
            name="regulator",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="regulatory_data.regulator"),
        ),
        migrations.AddField(
            model_name="expression",
            name="source",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="regulatory_data.datasource"),
        ),
        migrations.AddField(
            model_name="expression",
            name="uploader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_uploader",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="fileformat",
            field=models.ForeignKey(
                help_text="Foreign key to the FileFormat table",
                on_delete=django.db.models.deletion.CASCADE,
                to="regulatory_data.fileformat",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="modifier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_modifier",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="uploader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_uploader",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="callingcardsbackground",
            name="fileformat",
            field=models.ForeignKey(
                help_text="The file format of the file",
                on_delete=django.db.models.deletion.CASCADE,
                to="regulatory_data.fileformat",
            ),
        ),
        migrations.AddField(
            model_name="callingcardsbackground",
            name="modifier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_modifier",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="callingcardsbackground",
            name="uploader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_uploader",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="BindingManualQC",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upload_date", models.DateField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "best_datatype",
                    models.CharField(
                        choices=[("unreviewed", "unreviewed"), ("pass", "pass"), ("fail", "fail"), ("note", "note")],
                        default="unreviewed",
                        help_text="`pass` if the only binding data that performs better is from the same binding source. Otherwise, `unreviewed` or `fail`",
                    ),
                ),
                (
                    "data_usable",
                    models.CharField(
                        choices=[("unreviewed", "unreviewed"), ("pass", "pass"), ("fail", "fail"), ("note", "note")],
                        default="unreviewed",
                        help_text="`pass` if there is no reason to believe the data has technical faults. Otherwise, `unreviewed` or `false`",
                    ),
                ),
                (
                    "passing_replicate",
                    models.CharField(
                        choices=[("unreviewed", "unreviewed"), ("pass", "pass"), ("fail", "fail"), ("note", "note")],
                        default="unreviewed",
                        help_text="Primarily, and probably only, relevant to Calling Cards data. `pass` if the replicate's hops should be counted towards the target hop count. `unreviewed` or `false` otherwise",
                    ),
                ),
                (
                    "rank_recall",
                    models.CharField(
                        choices=[("unreviewed", "unreviewed"), ("pass", "pass"), ("fail", "fail"), ("note", "note")],
                        default="unreviewed",
                        help_text="`pass` if at least 1 rank response bin in the first 100 genes ranked by pvalue is significant. Else `unreviewed` or `fail`",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        default="none",
                        help_text="Free entry field for notes from the manual QC review",
                        max_length=100,
                    ),
                ),
                (
                    "binding",
                    models.OneToOneField(
                        help_text="Foreign key to the Binding table",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regulatory_data.binding",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modifier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_uploader",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bindingmanualqc",
            },
        ),
        migrations.AddField(
            model_name="binding",
            name="regulator",
            field=models.ForeignKey(
                help_text="Foreign key to the Regulator table",
                on_delete=django.db.models.deletion.CASCADE,
                to="regulatory_data.regulator",
            ),
        ),
        migrations.AddField(
            model_name="binding",
            name="source",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="regulatory_data.datasource"),
        ),
        migrations.AddField(
            model_name="binding",
            name="uploader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_uploader",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="promotersetsig",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("single_binding__isnull", False), ("composite_binding__isnull", False), _connector="OR"
                ),
                name="single_or_composite_binding_not_null",
            ),
        ),
        migrations.AddIndex(
            model_name="genomicfeature",
            index=models.Index(
                models.F("chr"), models.F("start"), models.F("end"), models.F("strand"), name="coord_index"
            ),
        ),
        migrations.AddConstraint(
            model_name="genomicfeature",
            constraint=models.CheckConstraint(check=models.Q(("start__gt", 0)), name="start_cannot_be_less_than_one"),
        ),
        migrations.AlterUniqueTogether(
            name="expression",
            unique_together={
                ("regulator", "batch", "strain", "replicate", "control", "mechanism", "restriction", "time", "source")
            },
        ),
        migrations.AlterUniqueTogether(
            name="datasource",
            unique_together={("lab", "assay", "workflow")},
        ),
        migrations.AlterUniqueTogether(
            name="binding",
            unique_together={("regulator", "batch", "condition", "replicate", "source")},
        ),
    ]
