# Generated by Django 4.2.8 on 2023-12-12 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bindingsource",
            old_name="fileformat_id",
            new_name="fileformat",
        ),
    ]
