# Generated by Django 4.2.8 on 2023-12-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expression",
            name="control",
            field=models.CharField(
                choices=[("undefined", "undefined"), ("wt", "wt"), ("wt_mata", "wt_mata")],
                default="undefined",
                help_text="Intended for micro-array data, this field records the control strain used to generate the relative intensity data",
            ),
        ),
    ]
