# Generated by Django 4.2.8 on 2024-07-02 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bindingconcatenated",
            name="regulator",
            field=models.ForeignKey(
                help_text="Foreign key to the Regulator table",
                on_delete=django.db.models.deletion.CASCADE,
                to="regulatory_data.regulator",
            ),
        ),
        migrations.AddField(
            model_name="bindingconcatenated",
            name="source",
            field=models.ForeignKey(
                help_text="Foreign key to the DataSource table",
                on_delete=django.db.models.deletion.CASCADE,
                to="regulatory_data.datasource",
            ),
        ),
        migrations.AlterField(
            model_name="bindingconcatenated",
            name="bindings",
            field=models.ManyToManyField(
                help_text="Many to many relationship with the Binding table", to="regulatory_data.binding"
            ),
        ),
    ]
