# Generated by Django 4.2.8 on 2023-12-21 02:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bindingmanualqc",
            old_name="best_response_pass",
            new_name="best_datatype",
        ),
        migrations.RenameField(
            model_name="regulator",
            old_name="regulator",
            new_name="genomicfeature",
        ),
        migrations.RemoveField(
            model_name="bindingmanualqc",
            name="rank_response_pass",
        ),
    ]
