# Generated by Django 4.2.8 on 2023-12-12 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0002_rename_fileformat_id_bindingsource_fileformat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expressionsource",
            old_name="fileformat_id",
            new_name="fileformat",
        ),
    ]
