# Generated by Django 4.2.8 on 2024-07-02 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("regulatory_data", "0002_bindingconcatenated_regulator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bindingconcatenated",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="bindingconcatenated",
            name="modifier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_modifier",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bindingconcatenated",
            name="upload_date",
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bindingconcatenated",
            name="uploader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_uploader",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
