# Generated by Django 4.2.8 on 2024-01-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0002_rename_best_response_pass_bindingmanualqc_best_datatype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="description",
            field=models.CharField(
                default="none",
                help_text="A description of the data. include a URL to github repo with scripts describing how the data was parsed",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="notes",
            field=models.CharField(
                default="none", help_text="Any additional notes about the source of the binding data", max_length=200
            ),
        ),
    ]
