# Generated by Django 4.2.8 on 2023-12-15 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0002_alter_expression_control"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="name",
            field=models.CharField(
                db_index=True,
                default="none",
                help_text="A unique name for the data source, eg 'chipexo_pugh_allevents",
                max_length=50,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="binding",
            name="regulator",
            field=models.ForeignKey(
                help_text="Foreign key to the Regulator table",
                on_delete=django.db.models.deletion.CASCADE,
                to="regulatory_data.regulator",
            ),
        ),
        migrations.AlterField(
            model_name="fileformat",
            name="fileformat",
            field=models.CharField(
                db_index=True,
                help_text="A file format name. This should be short, eg 'bed' or 'qbed' or 'tsv'",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="genomicfeature",
            name="locus_tag",
            field=models.CharField(
                db_index=True,
                default="unknown",
                help_text="CharField with a max length of 20 and a unique constraint, representing the locus tag of the feature, eg YAL001C",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="genomicfeature",
            name="strand",
            field=models.CharField(
                choices=[("+", "+"), ("-", "-"), ("*", "*")],
                default="*",
                help_text="strand of the feature, one of +, -, or *",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="genomicfeature",
            name="symbol",
            field=models.CharField(
                db_index=True,
                default="unknown",
                help_text="CharField with a max length of 20, representing the feature symbol (eg GAL4)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="promoterset",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="The name of the promoter set, eg `orf` or `yiming`",
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="genomicfeature",
            index=models.Index(
                models.F("chr"), models.F("start"), models.F("end"), models.F("strand"), name="coord_index"
            ),
        ),
    ]
