# Generated by Django 4.2.8 on 2023-12-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0003_rename_fileformat_id_expressionsource_fileformat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promotersetsig",
            old_name="background_id",
            new_name="background",
        ),
        migrations.RenameField(
            model_name="promotersetsig",
            old_name="promoter_id",
            new_name="promoter",
        ),
        migrations.AlterField(
            model_name="expression",
            name="control",
            field=models.CharField(
                choices=[("undefined", "undefined"), ("wt", "wt"), ("wt_meta", "wt_meta")],
                default="undefined",
                help_text="Intended for micro-array data, this field records the control strain used to generate the relative intensity data",
            ),
        ),
    ]
