# Generated by Django 4.2.8 on 2024-07-04 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0003_bindingconcatenated_modified_date_and_more"),
    ]

    operations = [
        # Rename the field `binding` to `single_binding`
        migrations.RenameField(
            model_name="bindingmanualqc",
            old_name="binding",
            new_name="single_binding",
        ),
        # Alter the `single_binding` field to allow null and blank values
        # note that the renaming and this were added by hand
        migrations.AlterField(
            model_name="bindingmanualqc",
            name="single_binding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                help_text="Foreign key to the 'Binding' table",
                on_delete=django.db.models.deletion.CASCADE,
                to="regulatory_data.binding",
            ),
        ),
        # Add the `composite_binding` field
        migrations.AddField(
            model_name="bindingmanualqc",
            name="composite_binding",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to the 'BindingConcatenated' table",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="regulatory_data.bindingconcatenated",
            ),
        ),
        # Add the check constraint
        migrations.AddConstraint(
            model_name="bindingmanualqc",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("single_binding__isnull", False), ("composite_binding__isnull", False), _connector="OR"
                ),
                name="single_or_composite_binding_not_null_bindingmanualqc",
            ),
        ),
        # Add the unique constraints
        migrations.AddConstraint(
            model_name="bindingmanualqc",
            constraint=models.UniqueConstraint(
                fields=("single_binding",), name="unique_single_binding_bindingmanualqc"
            ),
        ),
        migrations.AddConstraint(
            model_name="bindingmanualqc",
            constraint=models.UniqueConstraint(
                fields=("composite_binding",), name="unique_composite_binding_bindingmanualqc"
            ),
        ),
    ]
