# Generated by Django 4.2.8 on 2024-07-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0004_remove_bindingmanualqc_binding_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bindingconcatenated",
            constraint=models.UniqueConstraint(
                fields=("regulator", "source"), name="unique_regulator_source_bindingconcatenated"
            ),
        ),
    ]
