# Generated by Django 4.2.8 on 2023-12-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0004_rename_background_id_promotersetsig_background_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genomicfeature",
            name="biotype",
        ),
        migrations.AlterField(
            model_name="genomicfeature",
            name="type",
            field=models.CharField(
                default="unknown",
                help_text="CharField with a max length of 30, representing the type of the genomic feature, eg 'gene' or 'tRNA_gene'",
                max_length=30,
            ),
        ),
    ]
