# Generated by Django 4.2.8 on 2023-12-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0004_fileformat_default_effect_threshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rankresponse",
            name="significant_response",
            field=models.BooleanField(
                default=False,
                help_text="This field is used to indicate whether there are any bins in the top 250 genes with a confidence interval that does not include 0",
            ),
        ),
    ]
