# Generated by Django 4.2.8 on 2023-12-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0005_remove_genomicfeature_biotype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileformat",
            name="pval_col",
            field=models.CharField(
                default="none",
                help_text="The name of the column that should be used as the default p-value column. Eg 'pvalue'. Defaults to 'none' if there is no p-value column.",
                max_length=40,
            ),
        ),
    ]
