# Generated by Django 4.2.8 on 2024-10-30 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import yeastregulatorydb.regulatory_data.models.mixins.GzipFileUploadWithIdMixin


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("regulatory_data", "0005_bindingconcatenated_unique_regulator_source_bindingconcatenated"),
    ]

    operations = [
        migrations.CreateModel(
            name="RankResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upload_date", models.DateField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "parameters",
                    models.JSONField(
                        help_text="A json field to store parameters used to generate the rankresponse. The keys are 'bin_size' and 'bin_overlap'. The values are integers."
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="A csv which summarizes the responsiveness of a given TF, ranked by binding. The data is unsummarized but the column 'bin' allows for summarization",
                        upload_to="temp",
                    ),
                ),
                (
                    "expression",
                    models.ForeignKey(
                        help_text="Foreign key to the 'Expression' table",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expression",
                        to="regulatory_data.expression",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modifier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promotersetsig",
                    models.ForeignKey(
                        help_text="Foreign key to the 'PromoterSetSig' table",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotersetsig",
                        to="regulatory_data.promotersetsig",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_uploader",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rankresponse",
            },
            bases=(
                models.Model,
                yeastregulatorydb.regulatory_data.models.mixins.GzipFileUploadWithIdMixin.GzipFileUploadWithIdMixin,
            ),
        ),
    ]
