# Generated by Django 4.2.8 on 2024-12-03 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("regulatory_data", "0006_rankresponse"),
    ]

    operations = [
        migrations.CreateModel(
            name="DTO",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upload_date", models.DateField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "parameters",
                    models.JSONField(help_text="A json field to store the parameters used to generate the DTO result"),
                ),
                ("result", models.JSONField(help_text="A json field to store the result of DTO")),
                (
                    "expression",
                    models.OneToOneField(
                        help_text="Foreign key to the 'Expression' table",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dto_expression",
                        to="regulatory_data.expression",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modifier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promotersetsig",
                    models.OneToOneField(
                        help_text="One-to-one field to the 'PromoterSetSig' table",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dto_pss",
                        to="regulatory_data.promotersetsig",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_uploader",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dto",
                "managed": True,
            },
        ),
    ]
