# Generated by Django 4.2.8 on 2023-12-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0006_alter_fileformat_pval_col"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileformat",
            name="effect_col",
            field=models.CharField(
                default="none",
                help_text="The name of the column that should be used as the default effect column. Eg 'score'. Defaults to 'none' if there is no effect column.",
                max_length=40,
            ),
        ),
    ]
