# Generated by Django 4.2.8 on 2024-01-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0006_alter_promoterset_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binding",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="A file which stores data on regulator/DNA interaction",
                null=True,
                upload_to="temp",
            ),
        ),
        migrations.AlterField(
            model_name="promotersetsig",
            name="promoter",
            field=models.ForeignKey(
                blank=True,
                help_text="foreign key to the 'promoter' table",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="regulatory_data.promoterset",
            ),
        ),
    ]
