# Generated by Django 4.2.8 on 2024-12-03 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0007_dto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dto",
            options={},
        ),
        migrations.AlterField(
            model_name="dto",
            name="expression",
            field=models.ForeignKey(
                help_text="Foreign keys field to the 'Expression' table",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dto_expression",
                to="regulatory_data.expression",
            ),
        ),
        migrations.AlterField(
            model_name="dto",
            name="promotersetsig",
            field=models.ForeignKey(
                help_text="Foreign key field to the 'PromoterSetSig' table",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dto_pss",
                to="regulatory_data.promotersetsig",
            ),
        ),
        migrations.AddConstraint(
            model_name="dto",
            constraint=models.UniqueConstraint(
                fields=("promotersetsig", "expression"), name="unique_promotersetsig_expression"
            ),
        ),
    ]
