# Generated by Django 4.2.8 on 2023-12-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0007_alter_fileformat_effect_col"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promotersetsig",
            old_name="filetype",
            new_name="fileformat",
        ),
        migrations.AlterField(
            model_name="fileformat",
            name="fileformat",
            field=models.CharField(
                help_text="A file format name. This should be short, eg 'bed' or 'qbed' or 'tsv'",
                max_length=20,
                unique=True,
            ),
        ),
    ]
