# Generated by Django 4.2.8 on 2024-12-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0008_alter_dto_options_alter_dto_expression_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dto",
            name="passing_fdr",
            field=models.BooleanField(
                default=True,
                help_text="A boolean field which is `True` when FDR >= 0.2. See the DTO paper/software for more details",
            ),
        ),
        migrations.AddField(
            model_name="dto",
            name="passing_pvalue",
            field=models.BooleanField(
                default=True, help_text="A boolean field which is `True` when the empirical p-value <= 0.1"
            ),
        ),
        migrations.AddField(
            model_name="rankresponse",
            name="passing",
            field=models.BooleanField(
                default=True,
                help_text="A boolean field which is `True` if at least one bin is significant in the first 100.",
            ),
        ),
        migrations.AddField(
            model_name="rankresponse",
            name="rank_25",
            field=models.FloatField(default=0.0, help_text="The rank response at bin 25"),
        ),
        migrations.AddField(
            model_name="rankresponse",
            name="rank_50",
            field=models.FloatField(default=0.0, help_text="The rank response at bin 50"),
        ),
    ]
