# Generated by Django 4.2.8 on 2024-12-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0009_dto_passing_fdr_dto_passing_pvalue_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rankresponse",
            constraint=models.UniqueConstraint(
                fields=("promotersetsig", "expression"), name="unique_promotersetsig_expression_rankresponse"
            ),
        ),
    ]
