# Generated by Django 4.2.8 on 2024-01-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0009_alter_fileformat_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="binding",
            name="condition",
            field=models.CharField(
                choices=[
                    ("unknown", "unknown"),
                    ("YPD", "YPD"),
                    ("SM", "SM"),
                    ("RAPA", "RAPA"),
                    ("H2O2Hi", "H2O2Hi"),
                    ("H2O2Lo", "H2O2Lo"),
                    ("Acid", "Acid"),
                    ("Alpha", "Alpha"),
                    ("BUT14", "BUT14"),
                    ("BUT90", "BUT90"),
                    ("Thi-", "Thi-"),
                    ("GAL", "GAL"),
                    ("HEAT", "HEAT"),
                    ("Pi-", "Pi-"),
                    ("RAFF", "RAFF"),
                ],
                default="unknown",
                help_text="If the condition is known, it is provided. Otherwise, the value is `unknown`",
                max_length=20,
            ),
        ),
    ]
