# Generated by Django 4.2.8 on 2024-12-11 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0010_rankresponse_unique_promotersetsig_expression_rankresponse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bindingmanualqc",
            name="best_datatype",
        ),
        migrations.RemoveField(
            model_name="bindingmanualqc",
            name="passing_replicate",
        ),
        migrations.RemoveField(
            model_name="bindingmanualqc",
            name="rank_recall",
        ),
    ]
