# Generated by Django 4.2.8 on 2024-01-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0011_alter_binding_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="strain",
            field=models.CharField(
                default="undefined",
                help_text="The strain used in the experiment. This will be derived from the original data source. Default value is `undefined`",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="batch",
            field=models.CharField(
                db_index=True,
                default="undefined",
                help_text="A batch identifier for a set of data, eg the run number in the case of calling cards",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="control",
            field=models.CharField(
                choices=[("undefined", "undefined"), ("wt", "wt"), ("wt_mata", "wt_mata")],
                db_index=True,
                default="undefined",
                help_text="Intended for micro-array data, this field records the control strain used to generate the relative intensity data",
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="mechanism",
            field=models.CharField(
                choices=[("gev", "gev"), ("zev", "zev"), ("tfko", "tfko")],
                db_index=True,
                default="undefined",
                help_text="The mechanism by which the regulator was perturbed",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="replicate",
            field=models.PositiveIntegerField(db_index=True, default=1, help_text="Replicate number"),
        ),
        migrations.AlterField(
            model_name="expression",
            name="restriction",
            field=models.CharField(
                choices=[("undefined", "undefined"), ("P", "P"), ("M", "M"), ("N", "N")],
                db_index=True,
                default="undefined",
                help_text="This is a feature of the McIsaac ZEV data",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="time",
            field=models.PositiveIntegerField(
                db_index=True, default=0, help_text="Timepoint of the experiment in minutes"
            ),
        ),
    ]
