# Generated by Django 4.2.8 on 2024-12-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0011_remove_bindingmanualqc_best_datatype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bindingmanualqc",
            name="manual_fail",
            field=models.BooleanField(
                default=False,
                help_text="This provides a way of overriding the automated QC If it is set to `True`, a reason should be provided in the `notes` field",
            ),
        ),
    ]
