# Generated by Django 4.2.8 on 2024-12-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0012_bindingmanualqc_manual_fail"),
    ]

    operations = [
        migrations.AddField(
            model_name="bindingmanualqc",
            name="preferred_replicate",
            field=models.BooleanField(
                default=False,
                help_text="If `True`, this is the preferred replicate for a replicate binding set. This is intended to be used for data sources without aggregated replicates",
            ),
        ),
        migrations.AddField(
            model_name="expressionmanualqc",
            name="preferred_replicate",
            field=models.BooleanField(
                default=False,
                help_text="Where replicates or multiple conditions exist, this field indicates the preferred replicate for analysis",
            ),
        ),
    ]
