# Generated by Django 4.2.8 on 2024-01-19 01:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0013_alter_expression_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="expression",
            unique_together={
                ("regulator", "batch", "strain", "replicate", "control", "mechanism", "restriction", "time", "source")
            },
        ),
    ]
