# Generated by Django 4.2.8 on 2024-12-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0013_bindingmanualqc_preferred_replicate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rankresponse",
            name="random_expectation",
            field=models.FloatField(default=0.0, help_text="The random expectation"),
        ),
        migrations.AddField(
            model_name="rankresponse",
            name="total_expression_genes",
            field=models.IntegerField(default=0, help_text="The total number of genes in the expression data"),
        ),
    ]
