# Generated by Django 4.2.8 on 2024-12-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0014_rankresponse_random_expectation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expressionmanualqc",
            name="notes",
            field=models.CharField(
                default="none", help_text="Free entry field for notes from the manual QC review", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="bindingmanualqc",
            name="notes",
            field=models.CharField(
                default="none", help_text="Free entry field for notes from the manual QC review", max_length=300
            ),
        ),
    ]
