# Generated by Django 4.2.8 on 2024-12-23 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("regulatory_data", "0015_expressionmanualqc_notes_alter_bindingmanualqc_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnivariateModels",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upload_date", models.DateField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("rsquared", models.FloatField(default=0.0, help_text="The R-squared value of the univariate model")),
                ("pvalue", models.FloatField(default=0.0, help_text="The p-value of the univariate model")),
                ("coefficients", models.JSONField(help_text="The coefficients of the univariate model")),
                (
                    "expression",
                    models.ForeignKey(
                        help_text="Foreign key to the 'Expression' table",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="um_expression",
                        to="regulatory_data.expression",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modifier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promotersetsig",
                    models.ForeignKey(
                        help_text="Foreign key to the 'PromoterSetSig' table",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="um_promotersetsig",
                        to="regulatory_data.promotersetsig",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_uploader",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "univariatemodels",
            },
        ),
        migrations.AddConstraint(
            model_name="univariatemodels",
            constraint=models.UniqueConstraint(
                fields=("promotersetsig", "expression"), name="unique_promotersetsig_expression_univariatemodels"
            ),
        ),
    ]
