# Generated by Django 4.2.8 on 2024-03-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0016_alter_bindingmanualqc_best_datatype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expression",
            name="time",
            field=models.FloatField(db_index=True, default=0, help_text="Timepoint of the experiment in minutes"),
        ),
    ]
