# Generated by Django 4.2.8 on 2025-02-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0016_univariatemodels_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rankresponse",
            name="rank_25",
            field=models.FloatField(blank=True, help_text="The rank response at bin 25", null=True),
        ),
        migrations.AlterField(
            model_name="rankresponse",
            name="rank_50",
            field=models.FloatField(blank=True, help_text="The rank response at bin 50", null=True),
        ),
    ]
