# Generated by Django 4.2.8 on 2024-06-27 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0017_alter_expression_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotersetsig",
            name="binding",
        ),
        migrations.AddField(
            model_name="promotersetsig",
            name="single_binding",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to the 'Binding' table",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promoter_set_sigs",
                to="regulatory_data.binding",
            ),
        ),
        migrations.CreateModel(
            name="BindingConcatenated",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "genomic_inserts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of inserts which map to chromosomes labelled as `genomic` in the ChrMap table",
                    ),
                ),
                (
                    "mito_inserts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of inserts which map to chromosomes labelled as mitochondrial in the ChrMap table",
                    ),
                ),
                (
                    "plasmid_inserts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of inserts which map to contigs labelled as plasmid in the ChrMap table",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        default="none", help_text="Free entry text field, no more than 100 char long", max_length=100
                    ),
                ),
                ("bindings", models.ManyToManyField(to="regulatory_data.binding")),
            ],
            options={
                "db_table": "bindingconcatenated",
            },
        ),
        migrations.AddField(
            model_name="promotersetsig",
            name="composite_binding",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to the 'BindingConcatenated' table",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promoter_set_sigs",
                to="regulatory_data.bindingconcatenated",
            ),
        ),
    ]
