# Generated by Django 4.2.8 on 2025-05-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0017_alter_rankresponse_rank_25_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dto",
            index=models.Index(fields=["expression", "promotersetsig"], name="idx_expression_pss"),
        ),
        migrations.AddIndex(
            model_name="rankresponse",
            index=models.Index(fields=["expression", "promotersetsig"], name="idx_expr_pss_rr"),
        ),
        migrations.AddIndex(
            model_name="univariatemodels",
            index=models.Index(fields=["expression", "promotersetsig"], name="idx_expr_pss_univariatemodels"),
        ),
    ]
