# Generated by Django 4.2.8 on 2024-06-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0018_remove_promotersetsig_binding_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="promotersetsig",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("single_binding__isnull", False), ("composite_binding__isnull", False), _connector="OR"
                ),
                name="single_or_composite_binding_not_null",
            ),
        ),
    ]
