# Generated by Django 4.2.8 on 2024-06-27 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory_data", "0019_promotersetsig_single_or_composite_binding_not_null"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RankResponse",
        ),
    ]
