# Generated by Django 4.2.8 on 2024-02-10 18:28

from django.db import migrations


def update_site_domain(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    # Update the site domain and name
    # Assuming the default SITE_ID is 1
    site = Site.objects.filter(id=1).first()
    if site:
        site.domain = 'yeastregulatorydb.com'
        site.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0004_alter_options_ordering_domain"),
    ]

    operations = [
        migrations.RunPython(update_site_domain),
    ]
