# Generated by Django 4.2.8 on 2025-05-05 15:33

from django.db import migrations


def update_site_domain(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    # Update the site domain and name
    # Assuming the default SITE_ID is 1
    site = Site.objects.filter(id=1).first()
    if site:
        site.domain = "tfbindingandperturbation.com"
        site.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0005_auto_20240210_1228"),
    ]

    operations = [
        migrations.RunPython(update_site_domain),
    ]
