# Generated by Django 4.2.8 on 2025-05-05 17:27
# generated with this cmd
# python manage.py makemigrations sites --empty \
#     --name update_domain_django_tfbindingpert
# and then edited based on previous domain update migrations

from django.db import migrations


def update_site_domain(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    # Update the site domain and name
    # Assuming the default SITE_ID is 1
    site = Site.objects.filter(id=1).first()
    if site:
        site.domain = "django.tfbindingandperturbation.com"
        site.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0006_update_domain_tfbindingandperturbation"),
    ]

    operations = [
        migrations.RunPython(update_site_domain),
    ]
